from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from apps.farms.models import Field


class Recommendation(models.Model):
    """
    Crop recommendations generated by the ML model.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recommendations')
    field = models.ForeignKey(Field, on_delete=models.CASCADE, related_name='recommendations')
    crop_name = models.CharField(max_length=100, help_text="Recommended crop name")
    confidence_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Confidence score (0-100)"
    )
    expected_yield = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(0)],
        help_text="Expected yield in kg/hectare"
    )
    profit_margin = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text="Expected profit margin in local currency"
    )
    sustainability_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Sustainability score (0-100)"
    )
    reasoning = models.JSONField(
        default=dict,
        blank=True,
        help_text="Detailed reasoning for the recommendation in JSON format"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Recommendation"
        verbose_name_plural = "Recommendations"
        ordering = ['-confidence_score', '-created_at']

    def __str__(self):
        return f"{self.crop_name} for {self.field.name} (Confidence: {self.confidence_score}%)"
