# Generated by Django 4.2.7 on 2025-11-07 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Location latitude', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Location longitude', max_digits=9)),
                ('date', models.DateField(help_text='Date of the weather data')),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, help_text='Rainfall in mm', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Humidity percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('wind_speed', models.DecimalField(decimal_places=2, help_text='Wind speed in km/h', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('forecast_data', models.JSONField(blank=True, default=dict, help_text='Additional forecast data in JSON format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('latitude', 'longitude', 'date')},
            },
        ),
    ]
