# Generated by Django 4.2.7 on 2025-11-07 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(decimal_places=2, help_text='Soil pH level (typically 0-14)', max_digits=4)),
                ('moisture', models.DecimalField(decimal_places=2, help_text='Soil moisture percentage', max_digits=5)),
                ('n', models.DecimalField(decimal_places=2, help_text='Nitrogen content in kg/hectare', max_digits=6)),
                ('p', models.DecimalField(decimal_places=2, help_text='Phosphorus content in kg/hectare', max_digits=6)),
                ('k', models.DecimalField(decimal_places=2, help_text='Potassium content in kg/hectare', max_digits=6)),
                ('source', models.CharField(choices=[('satellite', 'Satellite Data'), ('iot', 'IoT Sensor'), ('manual', 'Manual Input'), ('soil_grids', 'Soil Grids API'), ('bhuvan', 'Bhuvan API')], default='manual', help_text='Source of the soil data', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to='farms.field')),
            ],
            options={
                'verbose_name': 'Soil Data',
                'verbose_name_plural': 'Soil Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
