# Generated by Django 4.2.7 on 2025-11-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soildata',
            name='k',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potassium content in kg/hectare', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='moisture',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soil moisture percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='n',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nitrogen content in kg/hectare', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Phosphorus content in kg/hectare', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soil pH level (typically 0-14)', max_digits=4, null=True),
        ),
    ]
