# Generated by Django 4.2.30 on 2026-05-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0002_alter_soildata_k_alter_soildata_moisture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soildata',
            name='source',
            field=models.CharField(choices=[('satellite', 'Satellite Data'), ('iot', 'IoT Sensor'), ('manual', 'Manual Input'), ('soil_grids', 'Soil Grids API'), ('bhuvan', 'Bhuvan API'), ('virtual_bhuvan', 'Regional Estimate (Virtual Bhuvan)')], default='manual', help_text='Source of the soil data', max_length=20),
        ),
    ]
