# Generated by Django 4.2.7 on 2025-11-07 09:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='Recommended crop name', max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Confidence score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_yield', models.DecimalField(decimal_places=2, help_text='Expected yield in kg/hectare', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('profit_margin', models.DecimalField(decimal_places=2, help_text='Expected profit margin in local currency', max_digits=10)),
                ('sustainability_score', models.DecimalField(decimal_places=2, help_text='Sustainability score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reasoning', models.JSONField(blank=True, default=dict, help_text='Detailed reasoning for the recommendation in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='farms.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
    ]
