# Generated by Django 4.2.7 on 2025-11-07 09:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the farm', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Farm location latitude', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Farm location longitude', max_digits=9)),
                ('area', models.DecimalField(decimal_places=2, help_text='Farm area in hectares', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silt', 'Silt'), ('peat', 'Peat'), ('chalky', 'Chalky'), ('unknown', 'Unknown')], default='unknown', help_text='Type of soil in the farm', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the field', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Field center latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Field center longitude', max_digits=9, null=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='Field area in hectares', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=2, help_text='Soil pH level', max_digits=4, null=True)),
                ('soil_moisture', models.DecimalField(blank=True, decimal_places=2, help_text='Soil moisture percentage', max_digits=5, null=True)),
                ('n_content', models.DecimalField(blank=True, decimal_places=2, help_text='Nitrogen content (kg/ha)', max_digits=6, null=True)),
                ('p_content', models.DecimalField(blank=True, decimal_places=2, help_text='Phosphorus content (kg/ha)', max_digits=6, null=True)),
                ('k_content', models.DecimalField(blank=True, decimal_places=2, help_text='Potassium content (kg/ha)', max_digits=6, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['farm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CropHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='Name of the crop grown', max_length=100)),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Monsoon)'), ('rabi', 'Rabi (Winter)'), ('zaid', 'Zaid (Summer)'), ('year_round', 'Year Round')], help_text='Season when crop was grown', max_length=20)),
                ('year', models.IntegerField(help_text='Year when crop was grown')),
                ('yield_achieved', models.DecimalField(blank=True, decimal_places=2, help_text='Yield achieved in kg/hectare', max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, help_text='Profit made in local currency', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the crop', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_history', to='farms.field')),
            ],
            options={
                'verbose_name': 'Crop History',
                'verbose_name_plural': 'Crop Histories',
                'ordering': ['-year', '-season'],
                'unique_together': {('field', 'crop_name', 'season', 'year')},
            },
        ),
    ]
